In [1]:
import gymnasium as gym
import numpy as np
from ai_trainer import *

I0000 00:00:1790573387.492695 1636607 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1790573387.518611 1636607 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1790573388.130041 1636607 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [2]:
gym.register("gymnasium_env/Ballz-v0", entry_point=BallzEnv, max_episode_steps=100)

In [3]:
env = gym.make("gymnasium_env/Ballz-v0", width=700, height=950, nblocks=7, render_mode="human")

In [4]:
env.observation_space

Dict('blocks': Box(0.0, 1.0, (10, 7, 2), float32), 'nballs': Box(0.0, 1.0, (), float32), 'position': Box(0.0, 1.0, (), float32))

In [5]:
agent = BallzAgent(env)

W0000 00:00:1790573388.767308 1636607 gpu_device.cc:2459] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
W0000 00:00:1790573388.776053 1636607 gpu_device.cc:2459] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0a. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1790573388.863332 1636607 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5854 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 12.0a


In [ ]:
rewards = agent.train(10000, live_plot=True)

/home/Tasan/Coding/ballz/for_training/trainVenv/lib/python3.12/site-packages/gymnasium/spaces/box.py:415: UserWarning: WARN: Casting input x to numpy array.
  gym.logger.warn("Casting input x to numpy array.")
I0000 00:00:1790573389.514397 1636607 cuda_dnn.cc:461] Loaded cuDNN version 92600
/home/Tasan/Coding/ballz/for_training/trainVenv/lib/python3.12/site-packages/gymnasium/spaces/box.py:415: UserWarning: WARN: Casting input x to numpy array.
  gym.logger.warn("Casting input x to numpy array.")
/home/Tasan/.pyenv/versions/3.12.14/lib/python3.12/tkinter/__init__.py:862: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  func(*args)


In [6]:
obs_list = []
for i in range(5):
    obs, _ = env.reset()
    for j in range(i):
        obs = env.step(0)[0]
    obs_list.append(obs)
    o_tens = agent.forward(obs)
    print(agent.actor(o_tens).numpy())
    print(agent.critic(o_tens).numpy())

/home/Tasan/Coding/ballz/for_training/trainVenv/lib/python3.12/site-packages/gymnasium/utils/passive_env_checker.py:157: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/home/Tasan/Coding/ballz/for_training/trainVenv/lib/python3.12/site-packages/gymnasium/spaces/box.py:415: UserWarning: WARN: Casting input x to numpy array.
  gym.logger.warn("Casting input x to numpy array.")
I0000 00:00:1790566227.430472 1577375 cuda_dnn.cc:461] Loaded cuDNN version 92600


[[-0.10868687  0.07445781]]
[[0.07435672]]


/home/Tasan/Coding/ballz/for_training/trainVenv/lib/python3.12/site-packages/gymnasium/spaces/box.py:415: UserWarning: WARN: Casting input x to numpy array.
  gym.logger.warn("Casting input x to numpy array.")


[[-0.07814617  0.07021748]]
[[0.02651924]]
[[-0.08139187  0.08267203]]
[[0.04568155]]
[[-0.08383746  0.06880607]]
[[-0.00652031]]
[[-0.0608547   0.06725661]]
[[0.02591737]]


In [7]:
rewards = agent.train(20, live_plot=True)

In [8]:
for obs in obs_list:
    o_tens = agent.forward(obs)
    print(agent.actor(o_tens).numpy())
    print(agent.critic(o_tens).numpy())

[[-0.18691789  0.37916705]]
[[-0.43368128]]
[[-0.09640358  0.2694733 ]]
[[-0.34011203]]
[[-0.08910055  0.2401901 ]]
[[-0.3289723]]
[[-0.07217319  0.2072776 ]]
[[-0.35640177]]
[[-0.05264835  0.23614249]]
[[-0.37481424]]


In [ ]:
for obs in obs_list:
    o_tens = agent.forward(obs)
    print(agent.actor(o_tens).numpy())

In [ ]:
rewards

In [ ]:
import matplotlib.pyplot as plt
plt.plot(agent.c_losses)
plt.xlabel('epoch')
plt.ylabel('losses')
